version: "3.8"

services:
  app:
    build: .
    ports:
      - "7860:7860"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_URL=http://host.docker.internal:11434
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A worker worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_URL=http://host.docker.internal:11434
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6380:6379"
